language: node_js
node_js: '12.2'

dist: trusty
sudo: false

# This caches $HOME/.npm or node_modules, depending on the repository’s structure
cache: npm

notifications:
    email:
        on_success: never
        on_failure: change

install:
    - npm install
    - npm install -g codecov

before_script:
    - npm rebuild node-sass

script:
    - npm run build:github || travis_terminate 1;
    - npm run flow || travis_terminate 1;
    - npm run test || travis_terminate 1;
    # - npm run ui-tests || travis_terminate 1;

after_success:
    - npm run test:coverage || travis_terminate 1;
    - codecov -t $CODECOV_TOKEN -f coverage/*

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
        branch: master
