language: node_js
node_js: '12.2'

dist: trusty
sudo: false

# This caches $HOME/.npm or node_modules, depending on the repository’s structure
cache: npm

notifications:
    email:
        on_success: never
        on_failure: change

install:
    - npm install

before_script:
    - npm rebuild node-sass

script:
    - npm run build --if-present
    - npm run flow
    - npm test
