language: node_js
node_js: '12.2'

dist: trusty
sudo: false

# This caches $HOME/.npm or node_modules, depending on the repository’s structure
cache: npm

notifications:
    email:
        on_success: never
        on_failure: change

install:
    - npm install

before_script:
    - npm rebuild node-sass

script:
    - npm run build:github
    - npm run flow
    - npm test

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
        branch: master
