name: main ci

on:
    push:
        branches:
            - 'main'
            - 'dev-*'

jobs:
    npm:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Install node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Checkout 🛎️
              uses: actions/checkout@v2

            - name: Install 🛠
              run: npm install

            - name: Build 📦
              env:
                  API_URL: TOTAL_FAKE
                  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_DEV }}
                  FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_DEV }}
                  USE_HASH_ROUTER: true
              run: |
                  envsubst < util/.env.template > .env
                  npm run build

            - name: Test 🔌
              run: npm run test:coverage

            - name: Publish Codecov 📈
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: coverage/*

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  ACCESS_TOKEN: '${{ secrets.GITHUB_PAGES }}'
                  BRANCH: gh-pages
                  FOLDER: build

    docker-dev:
        needs: npm
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2
            - name: Deploy to heroku (dev) 🚀
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_PASSWORD }}
                  API_URL: ${{ secrets.API_URL_DEV }}
                  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_DEV }}
                  FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_DEV }}
                  USE_HASH_ROUTER: false
              run: |
                  wget -qO- https://cli-assets.heroku.com/install.sh | sh
                  echo "${{ secrets.HEROKU_PASSWORD }}" | docker login -u "${{ secrets.HEROKU_USERNAME }}" --password-stdin registry.heroku.com
                  envsubst < util/.env.template > .env
                  heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}-dev
                  heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}-dev

    docker-prod:
        needs: npm
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2
            - name: Deploy to heroku (prod) 🚀
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_PASSWORD }}
                  API_URL: ${{ secrets.API_URL_PROD }}
                  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_PROD }}
                  FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_PROD }}
                  USE_HASH_ROUTER: false
              run: |
                  wget -qO- https://cli-assets.heroku.com/install.sh | sh
                  echo "${{ secrets.HEROKU_PASSWORD }}" | docker login -u "${{ secrets.HEROKU_USERNAME }}" --password-stdin registry.heroku.com
                  envsubst < util/.env.template > .env
                  heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}
                  heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
